### ISSUE TITLE
Can we run live/hot reload dev mode for HTML5 ?

### ISSUE THREAD

**Issue by nvcken** [openfl/openfl-samples#52]

**Comment by nvcken** [comment]
Cool, try NPM based samples now.
would you please add `-watch` hints on `openfl --help` would be good I thought?

**Comment by jgranick** [comment]
It's a little bit hidden, if you run `openfl help build` (or a similar command) then it shows up under "Experimental Options"

**Comment by nvcken** [comment]
Bravo, I found them now, thanks so much
